### ISSUE TITLE
"EnableWhen" Error

### ISSUE THREAD

**Issue by kirubel22** [lhncbc/formbuilder-lhcforms#1]
I was unable to upload fhir questionnaire (R4)into the NLM form builder if "enable when" extension is used. The error I am getting is as follows: "Cannot read property 'type' of undefined: Failed to convert the selected FHIR Questionnaire. File loading is aborted." 
If I remove all "enable when" options, the form does upload without a problem. 

In addition, even if I create a form using the NLM tool and upload it to FHIR server, I will get the same error if I try to import it back to the tool.

**Comment by akanduru** [comment]
Can you create a sample questionnaire that produces the error?

**Comment by kirubel22** [comment]
{
  "name": "New Form",
  "status": "draft",
  "title": "New Form",
  "resourceType": "Questionnaire",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire|3.5"
    ]
  },
  "item": [
    {
      "type": "group",
      "code": [
        {
          "code": "1",
          "display": "Protocol",
          "system": "Custom"
        }
      ],
      "required": false,
      "linkId": "/1",
      "text": "Protocol",
      "item": [
        {
          "type": "choice",
          "code": [
            {
              "code": "2",
              "display": "Type",
              "system": "Custom"
            }
          ],
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-item-control",
                    "code": "drop-down",
                    "display": "Drop down"
                  }
                ],
                "text": "Drop down"
              }
            }
          ],
          "required": false,
          "linkId": "/1/2",
          "text": "Type",
          "answerOption": [
            {
              "valueCoding": {
                "code": "c1",
                "display": "Intervention"
              }
            },
            {
              "valueCoding": {
                "code": "c2",
                "display": "Observation"
              }
            }
          ]
        },
        {
          "type": "string",
          "code": [
            {
              "code": "3",
              "display": "Intervention Type",
              "system": "Custom"
            }
          ],
          "required": false,
          "linkId": "/1/3",
          "text": "Intervention Type",
          "enableWhen": [
            {
              "question": "/1/2",
              "answerCoding": {
                "code": "c1"
              }
            }
          ]
        }
      ]
    }
  ]
}

**Comment by kirubel22** [comment]
[Test.zip](https://github.com/lhncbc/formbuilder-lhcforms/files/3473500/Test.zip)

**Comment by akanduru** [comment]
The linkid is invalid in enableWhen.question (item[0].item[5].item[1].item[4].enableWhen[0].question).  If you change it from "/1/52/55/59" to "59" it should work.

Here is the spec for [enableWhen.question](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.enableWhen.questionl)

**Comment by kirubel22** [comment]
Thanks. I provided "59" as a link ID but the form builder is appending the forward slashes and parent link IDs when I generate SDC Questionnaire.

**Comment by akanduru** [comment]
You are right. It is a bug to assign a code path, when you have linkid. I will fix it.

**Comment by kirubel22** [comment]
Thanks.

**Comment by plynchnlm** [comment]
@kirubel22 -- Since he hasn't fixed it *yet*, it is better not to close this.  I am reopening it until it is fixed.

**Comment by akanduru** [comment]
@kirubel22 -- The fix is promoted to the site. Please let us know if you notice any issues.
Thanks.
