### ISSUE TITLE
Can formbuilder generate linkId?

### ISSUE THREAD

**Issue by yunwwang** [lhncbc/formbuilder-lhcforms#2]
Hi, I am testing to use NLM Form Builder (https://lhcformbuilder.nlm.nih.gov) to create Questionnaire. First I am not sure if this is the correct place to ask question for that web site. My question is that when I add an item to the form, how do I specify item.linkId?

**Comment by plynchnlm** [comment]
I see this is closed, so perhaps you discovered that the form builder generates the linkId for you.

This is a good place to ask questions for the NLM Form Builder.  This package is the open-source portion of that website.
