### ISSUE TITLE
Customize display feature for choices and open choices missing in new editor

### ISSUE THREAD

**Issue by whollervi** [lhncbc/formbuilder-lhcforms#63]
Are there any plans to port / re-implement the 'Customize display' functionality (e.g. radio buttons or checkboxes for choice and open choice questions), like it was available in the previous version of the editor (under advanced item attributes)? Having checkboxes or radio buttons reduces the number of clicks, especially for questions having only a few answers. 

Current work-around is to first save the form on disk and manually add the FHIR extension where needed ...

Thanks for building the NLM Form builder, I am not aware of a better editor to create FHIR questionnaires!

**Comment by plynchnlm** [comment]
Yes, we are planning to add that back in, perhaps within the next couple of weeks.

**Comment by whollervi** [comment]
Glad that you will add it back! 

Today I had a look at the gtable extension for groups, which is already supported by lhc forms. Looks like this is a low hanging fruit, which you might consider to implement as well.

Thanks again!

**Comment by plynchnlm** [comment]
Unfortunately, I confused another task with the task for adding radio button and checkbox support back, so this is delayed.  However, we should be working on it within the next 2-3 weeks.

**Comment by akanduru** [comment]
The feature to layout answer list using check boxes and radio buttons is in the latest release 9.2.2.
