### ISSUE TITLE
ordinalValue extension doesn't work

### ISSUE THREAD

**Issue by Rosnyni** [lhncbc/formbuilder-lhcforms#64]
with (open-)choice type item, using 'Answer options' solution for 'Answer list source', it is possible to provide score for each answer option. 

The JSON created may contain some of the scores provided in the form builder, but rarely all of them : 

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/61731606/cfb97e03-cb38-4477-8ced-d9f286f92e7c)

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/61731606/7c14e196-016a-49c4-89bf-e00a771bf9c6)

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/61731606/9d405f31-0c33-49d8-889a-b33c639cbb22)

[choice_item_score_test.R4.txt](https://github.com/lhncbc/formbuilder-lhcforms/files/12027034/choice_item_score_test.R4.txt)

**Comment by plynchnlm** [comment]
Thank you for reporting this.  The score fields are badly broken.  We are working on a fix.

**Comment by plynchnlm** [comment]
This is now fixed (as of version 9.1.4).
