### ISSUE TITLE
help text considered as item

### ISSUE THREAD

**Issue by Rosnyni** [lhncbc/formbuilder-lhcforms#65]
I'm not sure it is a bug, but filling the help text attributes lead to the creation of a new child item of type display in the Questions Tree. 

If it is not a bug, may be having some information on the child item informing the user that this item is the help text of his father item should be considered.

**Comment by plynchnlm** [comment]
Are you seeing that in the UI or in the JSON output?  In FHIR, help text for an item is itself a child item of the item, so it is normal to see that in the JSON output.

**Comment by Rosnyni** [comment]
I see it both in the JSON preview and in the UI : 

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/61731606/afabdbaa-3b01-4186-8cfd-25866c2f50f7)

the 'help text of item 0' item was created by filling the 'help text' attribute of the 'item 0'.

**Comment by plynchnlm** [comment]
Thanks the for screenshot.  I don't think that should be showing up.  In the previous version (still also available for now) it does not show up.  In current version, it is really odd to have a help text field one on item which then clears and generates a new child item in the tree, so I think this is something we need to fix.  Thanks for the report.

**Comment by Rosnyni** [comment]
Thank you for the huge work you providing with the formbuilder !

**Comment by akanduru** [comment]
This is fixed.
