### ISSUE TITLE
item selection in question tree is unclear/unconsistant with data in the current item part of the screen

### ISSUE THREAD

**Issue by Rosnyni** [lhncbc/formbuilder-lhcforms#71]
using edge (Version 120.0.2210.121 (Version officielle) (64 bits))

starting from scratch : the current item (item 0), is gray-lighted in the question tree

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/61731606/bcf6ee60-2d75-42b8-9d33-c8ee2ab57586)

adding a new item (Add new item button): the current item (New item 1), is yellow lighted in the question tree. item 0 is still gray-lighted. (The use of the 'more option' button in the question tree does not produce this bug. )

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/61731606/ce17f2dc-ca7c-4517-baa2-07ad095fd8c2)

selecting properly New item 1 in the question tree, modifiing it and creating it (on your server, thanks) : the grey title bar is consistant with the question tree (New item 1 modified). But the fields in the current item part of the screen correspond to item 0...

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/61731606/c927a8b6-dbfe-4e6f-90a2-d4ea04e3e0d0)

The consequences (as I feel) are : 
 - the user can't be sure on where he perform modification on the questionnaire
 - he can modify the wrong item without noticing it
 - the trust in the tool is reduced
 - maybe it is a possible source for other bug to build on

**Comment by plynchnlm** [comment]
I agree these are problems-- thanks for reporting them.

**Comment by plynchnlm** [comment]
These are fixed in 9.2.4 (and on https://lhcformbuilder.nlm.nih.gov/).

**Comment by Rosnyni** [comment]
Thank you !
