### ISSUE TITLE
Problem with complex extension, the inner extension is lost from the model

### ISSUE THREAD

**Issue by ghaliouss** [lhncbc/formbuilder-lhcforms#72]
Hello,
We have a problem when importing a questionnaire that contains complex extension. 
The data is lost and the inner extension is deleted from the model when we try to preview after clicking the button 'Edit question'

Here the test questionnaire used to reproduce the issue: 

[issue with complex extension.json](https://github.com/lhncbc/formbuilder-lhcforms/files/14063366/issue.with.complex.extension.json)

**Step to reproduce the issue:**

1. Import questionnaire from local file:

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/14861910/f2a07493-807d-4249-8c97-0f809c652a39)

2. Click to the button 'Edit questions'

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/14861910/908e4d69-a4fd-41f6-bb64-094bae0d4168)

3. Click to the button 'Preview' and verify the json (the R4 version)

the inner extension is lost in the model, we should have an extension like this:
`
"extension": [
        {
          "url": "https://test.fr/ig/fhir/StructureDefinition/new-extension",
          "extension": [
            {
              "url": "id",
              "valueInteger": 1
            }
          ]
        }
      ]
`
![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/14861910/463249ce-577a-44c1-bab2-777ab26d763a)

Can you fix this issue please ?

Thanks in advance.

**Comment by Rosnyni** [comment]
Hello, 

I'm working with @ghaliouss. 

Just to add that It makes hard for us to add in the formbuilder the [launch context extension](http://hl7.org/fhir/uv/sdc/STU3/StructureDefinition-sdc-questionnaire-launchContext.html) and some home-made quite complex extensions. 

Sincerely

**Comment by Rosnyni** [comment]
> I think the Form Builder should not be dropping anything it doesn't know about.

I think I agree with you. 

>  But, there might be a faster fix that allows one level of extension nesting which would solve the immediate problem.

I can't remember any extension with more than two level. I'm not sure it is possible ?

**Comment by plynchnlm** [comment]
> > But, there might be a faster fix that allows one level of extension nesting which would solve the immediate problem.
> 
> I can't remember any extension with more than two level. I'm not sure it is possible ?

I had the same question.  It is turns out that it is rare, but it does happen.  https://chat.fhir.org/#narrow/stream/179166-implementers/topic/extensions.20with.20grandchildren.3F

**Comment by akanduru** [comment]
Dropping the extension here is due to the bug, regardless of whether the extension is valid or not. The bug is fixed in 9.2.8.

At the moment, form builder is imposing structural validity to the questionnaire based on fhir.schema.json. We are not really checking for semantic validation errors.

@Rosnyni, I am closing the issue, since the core problem is addressed. Feel free to re-open it if you have more to add.

**Comment by Rosnyni** [comment]
Thank you
