### ISSUE TITLE
Bug when changing the type of an item having restrcition to a date, dateTime or time

### ISSUE THREAD

**Issue by ghaliouss** [lhncbc/formbuilder-lhcforms#73]
The restriction function does not support date, dateTime and time item, yet. Those types should be removed from typeToOptions, otherwise it will generate a bug when changing the type of an item that has a restriction (a decimal item with maxValue restriction for example) to a date/dateTime or time type (we will have a broken extension having only the restriction url in the extension of the changed item )

Steps to reproduce the bug:

1. create a decimal item having 'Maximum Value' and 'Minimum Value' as restrictions:
![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/14861910/acabe95d-94c3-4f90-8b94-c950fc936311)

2. change the type of the item to 'Date'

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/14861910/14a070c0-1c1e-4668-85c6-533c16be3626)

3. Verify the json from the preview: the two extensions still present in the model (but broken), we should not have those extension for date/time items

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/14861910/255bca64-d592-4841-bf1c-6b93e9ff676d)

**Comment by akanduru** [comment]
The PR from @ghaliouss is merged into 9.2.7.
