### ISSUE TITLE
Choosing the question for conditional display is ambiguous when having multiple items with the same text

### ISSUE THREAD

**Issue by ghaliouss** [LHNCBC/formbuilder-lhcforms#76]
As you can see for [this example](https://github.com/lhncbc/formbuilder-lhcforms/files/14482964/Enable-when-source-issue-when-many-item-having-the-same-text.R4.json)
, it's not clear which item is selected and choosed for conditional display when we have multiple items with the same text  (which is our case with some questionnaire.)

![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/14861910/21b7d656-a0da-413f-9a0f-95abdfc88148)

I think we should display the tree hierarchy sequence number concatenated with the item's text

**Comment by plynchnlm** [comment]
Thanks for pointing this out, and especially for the PR.
