### ISSUE TITLE
add a new function that copy the context node 

### ISSUE THREAD

**Issue by ghaliouss** [LHNCBC/formbuilder-lhcforms#78]
- the copy is recursive: when node has childs, childs are copied also.
- the linkId is generated automaticaly as a random 12 digits number
- 
![image](https://github.com/lhncbc/formbuilder-lhcforms/assets/14861910/e058c41a-9b7e-4a22-a733-0abc9826d937)

**Comment by plynchnlm** [comment]
Your PR is now merged-- thanks again for contributing!
