### ISSUE TITLE
security and audit

### ISSUE THREAD

**Issue by Rosnyni** [LHNCBC/formbuilder-lhcforms#83]
Hello, 

we forked from your project at the 9.1.6 version. 

we developped some new functionalities to adapt the FB to the needs of our institution (APHP) and we run audit tools (sonar) to highlight, and correct, flaws in "our" code. 

It also higligth some (not critical) flaws in "your" code : 

![image](https://github.com/NLM-LHC/formbuilder-lhcforms/assets/61731606/6a71214d-8bfb-419c-bdaa-cfc0ba9b0848)

Were you aware of these? 

And subsidiarily, would it be possible to have an insight on the quality/security checks you are implementing?

Sincerely

Nicolas

**Comment by plynchnlm** [comment]
I don't wish to go into too many specifics here, but we do code reviews of all changes, we do run source code scan tools.  However, in my experience, perhaps only 1% of the automated scan findings are something worth considering changing, and number of things that must be changed is still lower.  So, if you do find something you think we need to fix, please open an issue for it, and if you fix something, we would appreciate a pull request.
