### ISSUE TITLE
Import from fhir server with interceptors not work.

### ISSUE THREAD

**Issue by tnikolai2** [lhncbc/formbuilder-lhcforms#9]
Formbuilder shows "resources found from FHIR server" and empty list.
If use hapi fhir interceptors, server return Bundle without total field, but Bundle has entries. I think this is the problem.

**Comment by akanduru** [comment]
It shows the questionnaires stored by the user. Did you save any questionnaires in the FHIR server?

**Comment by tnikolai2** [comment]
Yes.

I register simple consent interceptor, that allow all.
`
public class Consent1 implements IConsentService {
     public ConsentOutcome canSeeResource(RequestDetails theRequestDetails, IBaseResource theResource, IConsentContextServices theContextServices) {
      return ConsentOutcome.PROCEED;
    }
}

. . .  
public class JpaRestfulServer extends BaseJpaRestfulServer {
  @Override
  protected void initialize() throws ServletException {
    super.initialize();
    registerInterceptor(new ConsentInterceptor(new Consent1()));
  }
`

1) If i comment registerInterceptor 
Formbuilder  show all data.    
localhost/fhir/Questionnaire  shows all data with total field

2) If i uncomment registerInterceptor 
Formbuilder  show empty page.    
localhost/fhir/Questionnaire  shows all data but without total field

**Comment by plynchnlm** [comment]
Thanks for reporting this.  A fix is under review.

**Comment by akanduru** [comment]
Removed the condition on Bundle.total to display entry[] items.
